/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal install. It is checked in here
// so the TypeScript project is complete before dependencies are installed.
